services:
  api:
    build:
      context: .
      dockerfile: src/ECommerce.WebApi/Dockerfile
    container_name: ecommerce-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__SqlServer: Server=sqlserver,1433;Database=ECommerceDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True
      KafkaSettings__SectionName: Kafka
      Kafka__BootstrapServers: host.docker.internal:9092
      Kafka__Topic: pedido
      Kafka__ClientId: ecommerce-api
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: src/ECommerce.Worker/Dockerfile
    container_name: ecommerce-worker
    environment:
      DOTNET_ENVIRONMENT: Development
      ConnectionStrings__SqlServer: Server=sqlserver,1433;Database=ECommerceDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True
      KafkaSettings__SectionName: Kafka
      Kafka__BootstrapServers: host.docker.internal:9092
      Kafka__Topic: pedido
      Kafka__ClientId: ecommerce-worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -C -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

volumes:
  sqlserver-data:
